base:
  mass: 0.02
  size:
    x: 0.04
    y: 0.04
    z: 0.04
  dx: -0.076
  dy: 0.06
  dz: 0.0045
  mesh: 'caster_base.stl'
  x_offset: -0.203
  y_offset: 0.085
  z_offset: 0.033

hub:
  mass: 0.02
  size:
    x: 0.04
    y: 0.04
    z: 0.04
  dx: -0.077
  dy: 0.0
  dz: -0.0475
  mesh: 'caster_wheel_support.stl'

wheel:
  mass: 0.5                 # Wheel mass in Kg
  radius: 0.025             # Wheel radius in m
  length: 0.02              # Wheel length in m, considering is as a cylinder
  mesh: 'caster_wheel.stl'  # Name of the mesh files. Leave it empty ('') to have a red wheel
  x_offset: 0.035
  dx: -0.02                 # ${-caster_base_size/2.0*0.8}
  dy: -1
  dz: -0.048
