left_wheel_name: left_wheel_joint
right_wheel_name: right_wheel_joint
button_name: button_joint
serial_device: /dev/ttyUSB_ARDUINO
baud_rate: 57600
timeout: 1000
enc_ticks_per_rev: 960
bumpers:
  left:
    name: left_bumper_joint
    dx: 0.12
    dy: 0.08
    dz: 0.05
  right:
    name: right_bumper_joint
    dx: 0.12
    dy: -0.08
    dz: 0.05
