mass: 0.120        # Wheel mass in Kg
radius: 0.055    # Wheel radius in m
length: 0.025     # Wheel length in m, considering is as a cylinder
mesh: '../components/wheel.stl'  # Leave it empty ('') to have a red wheel
scale: ''
x_offset: 0.205
y_offset: -0.028
z_offset: 0.02
