kimchi_interfaces/Position2D pose_estimate
---
geometry_msgs/PoseWithCovarianceStamped localized_pose
bool localized
---
geometry_msgs/PoseWithCovarianceStamped pose_feedback
float64[2] current_uncertainty
