# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kimchi.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kimchi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckimchi.proto\x12\x06kimchi\" \n\x0fIsAliveResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\"6\n\rRobotStateMsg\x12%\n\x05state\x18\x01 \x01(\x0e\x32\x16.kimchi.RobotStateEnum\"+\n\x04Pose\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05theta\x18\x03 \x01(\x02\"+\n\x08Velocity\x12\x0e\n\x06linear\x18\x01 \x01(\x02\x12\x0f\n\x07\x61ngular\x18\x02 \x01(\x02\"F\n\x03Map\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x1c\n\x06origin\x18\x02 \x01(\x0b\x32\x0c.kimchi.Pose\x12\x12\n\nresolution\x18\x03 \x01(\x02\"\x07\n\x05\x45mpty*y\n\x0eRobotStateEnum\x12\n\n\x06NO_MAP\x10\x00\x12\x1c\n\x18MAPPING_WITH_EXPLORATION\x10\x01\x12\x17\n\x13MAPPING_WITH_TELEOP\x10\x02\x12\x0e\n\nNAVIGATING\x10\x03\x12\n\n\x06TELEOP\x10\x04\x12\x08\n\x04IDLE\x10\x05\x32\xfa\x01\n\tKimchiApp\x12\x33\n\x07IsAlive\x12\r.kimchi.Empty\x1a\x17.kimchi.IsAliveResponse\"\x00\x12*\n\x07GetPose\x12\r.kimchi.Empty\x1a\x0c.kimchi.Pose\"\x00\x30\x01\x12+\n\x04Move\x12\x10.kimchi.Velocity\x1a\r.kimchi.Empty\"\x00(\x01\x12&\n\x06GetMap\x12\r.kimchi.Empty\x1a\x0b.kimchi.Map\"\x00\x12\x37\n\rGetRobotState\x12\r.kimchi.Empty\x1a\x15.kimchi.RobotStateMsg\"\x00\x42 \n\x0f\x63om.kimchi.grpcB\x0bKimchiProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kimchi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.kimchi.grpcB\013KimchiProtoP\001'
  _globals['_ROBOTSTATEENUM']._serialized_start=285
  _globals['_ROBOTSTATEENUM']._serialized_end=406
  _globals['_ISALIVERESPONSE']._serialized_start=24
  _globals['_ISALIVERESPONSE']._serialized_end=56
  _globals['_ROBOTSTATEMSG']._serialized_start=58
  _globals['_ROBOTSTATEMSG']._serialized_end=112
  _globals['_POSE']._serialized_start=114
  _globals['_POSE']._serialized_end=157
  _globals['_VELOCITY']._serialized_start=159
  _globals['_VELOCITY']._serialized_end=202
  _globals['_MAP']._serialized_start=204
  _globals['_MAP']._serialized_end=274
  _globals['_EMPTY']._serialized_start=276
  _globals['_EMPTY']._serialized_end=283
  _globals['_KIMCHIAPP']._serialized_start=409
  _globals['_KIMCHIAPP']._serialized_end=659
# @@protoc_insertion_point(module_scope)
