#!/usr/bin/env python3
"""
Plot data from CSV log files generated by the data logger node.

This script reads odometry and cmd_vel data from CSV files and creates
various plots for analysis.
"""

import argparse
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
import os


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description='Plot data from kimchi data logger CSV files'
    )
    parser.add_argument(
        '--odom',
        type=str,
        help='Path to odometry CSV file'
    )
    parser.add_argument(
        '--cmd_vel',
        type=str,
        help='Path to cmd_vel CSV file'
    )
    parser.add_argument(
        '--log_dir',
        type=str,
        help='Directory containing log files'
    )
    parser.add_argument(
        '--session',
        type=str,
        help='Session name to plot'
    )
    parser.add_argument(
        '--output',
        type=str,
        default='plots',
        help='Output directory for plots (default: plots)'
    )
    return parser.parse_args()


def quaternion_to_euler(x, y, z, w):
    """Convert quaternion to Euler angles (roll, pitch, yaw)."""
    # Roll (x-axis rotation)
    sinr_cosp = 2 * (w * x + y * z)
    cosr_cosp = 1 - 2 * (x * x + y * y)
    roll = np.arctan2(sinr_cosp, cosr_cosp)
    
    # Pitch (y-axis rotation)
    sinp = 2 * (w * y - z * x)
    pitch = np.where(np.abs(sinp) >= 1, np.copysign(np.pi / 2, sinp), np.arcsin(sinp))
    
    # Yaw (z-axis rotation)
    siny_cosp = 2 * (w * z + x * y)
    cosy_cosp = 1 - 2 * (y * y + z * z)
    yaw = np.arctan2(siny_cosp, cosy_cosp)
    
    return roll, pitch, yaw


def plot_odometry(df_odom, output_dir):
    """Plot odometry data."""
    if df_odom is None or df_odom.empty:
        print("No odometry data to plot")
        return
    
    # Create time column in seconds
    df_odom['time'] = df_odom['timestamp_sec'] + df_odom['timestamp_nsec'] * 1e-9
    df_odom['time'] = df_odom['time'] - df_odom['time'].iloc[0]
    
    # Convert quaternion to euler angles
    roll, pitch, yaw = quaternion_to_euler(
        df_odom['orient_x'].values,
        df_odom['orient_y'].values,
        df_odom['orient_z'].values,
        df_odom['orient_w'].values
    )
    df_odom['yaw'] = yaw
    
    # Create plots
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    fig.suptitle('Odometry Data', fontsize=16)
    
    # Plot 1: 2D trajectory
    axes[0, 0].plot(df_odom['pos_x'], df_odom['pos_y'], 'b-', linewidth=2)
    axes[0, 0].plot(df_odom['pos_x'].iloc[0], df_odom['pos_y'].iloc[0], 'go', 
                     markersize=10, label='Principio')
    axes[0, 0].plot(df_odom['pos_x'].iloc[-1], df_odom['pos_y'].iloc[-1], 'ro', 
                     markersize=10, label='Final')
    axes[0, 0].set_xlabel('X (m)')
    axes[0, 0].set_ylabel('Y (m)')
    axes[0, 0].set_title('Trayectoria del Robot')
    axes[0, 0].grid(True)
    axes[0, 0].legend()
    axes[0, 0].axis('equal')
    
    # Plot 2: Position over time
    axes[0, 1].plot(df_odom['time'], df_odom['pos_x'], 'r-', label='X')
    # axes[0, 1].plot(df_odom['time'], df_odom['pos_y'], 'g-', label='Y')
    axes[0, 1].set_xlabel('Tiempo (s)')
    axes[0, 1].set_ylabel('Posición (m)')
    axes[0, 1].set_title('Posición vs Tiempo')
    axes[0, 1].grid(True)
    axes[0, 1].set_ylim(17.5, 23)
    axes[0, 1].legend()
    # Plot 3: Yaw angle over time
    axes[1, 0].plot(df_odom['time'], np.degrees(df_odom['yaw']), 'b-', linewidth=2)
    axes[1, 0].set_xlabel('Tiempo (s)')
    axes[1, 0].set_ylabel('Ángulo de Yaw (grados)')
    axes[1, 0].set_title('Ángulo de Yaw vs Tiempo')
    axes[1, 0].grid(True)
    
    # Plot 4: Velocities over time
    axes[1, 1].plot(df_odom['time'], df_odom['linear_vel_x'], 'r-', label='Velocidad Lineal X')
    axes[1, 1].plot(df_odom['time'], df_odom['angular_vel_z'], 'b-', label='Velocidad Angular Z')
    axes[1, 1].set_xlabel('Tiempo (s)')
    axes[1, 1].set_ylabel('Velocidad (m/s o rad/s)')
    axes[1, 1].set_title('Velocidades vs Tiempo (desde Odometría)')
    axes[1, 1].grid(True)
    axes[1, 1].legend()
    
    plt.tight_layout()
    output_path = os.path.join(output_dir, 'odometry_plots.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Saved odometry plots to: {output_path}")
    plt.show()


def plot_cmd_vel(df_cmd, output_dir):
    """Plot cmd_vel data."""
    if df_cmd is None or df_cmd.empty:
        print("No cmd_vel data to plot")
        return
    
    # Create time column in seconds
    df_cmd['time'] = df_cmd['timestamp_sec'] + df_cmd['timestamp_nsec'] * 1e-9
    df_cmd['time'] = df_cmd['time'] - df_cmd['time'].iloc[0]
    
    # Create plots
    fig, axes = plt.subplots(2, 1, figsize=(15, 8))
    fig.suptitle('Velocity Commands', fontsize=16)
    
    # Plot 1: Linear velocities
    axes[0].plot(df_cmd['time'], df_cmd['linear_vel_x'], 'r-', label='Linear X')
    axes[0].plot(df_cmd['time'], df_cmd['linear_vel_y'], 'g-', label='Linear Y')
    axes[0].set_xlabel('Time (s)')
    axes[0].set_ylabel('Linear Velocity (m/s)')
    axes[0].set_title('Linear Velocity Commands')
    axes[0].grid(True)
    axes[0].legend()
    
    # Plot 2: Angular velocities
    axes[1].plot(df_cmd['time'], df_cmd['angular_vel_z'], 'b-', label='Angular Z')
    axes[1].set_xlabel('Tiempo (s)')
    axes[1].set_ylabel('Velocidad Angular (rad/s)')
    axes[1].set_title('Comandos de Velocidad Angular')
    axes[1].grid(True)
    axes[1].legend()
    
    plt.tight_layout()
    output_path = os.path.join(output_dir, 'cmd_vel_plots.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Saved cmd_vel plots to: {output_path}")
    plt.show()


def plot_comparison(df_odom, df_cmd, output_dir):
    """Plot comparison between commanded and actual velocities."""
    if df_odom is None or df_cmd is None or df_odom.empty or df_cmd.empty:
        print("Insufficient data for comparison plot")
        return
    
    # Create time columns
    df_odom['time'] = df_odom['timestamp_sec'] + df_odom['timestamp_nsec'] * 1e-9
    df_cmd['time'] = df_cmd['timestamp_sec'] + df_cmd['timestamp_nsec'] * 1e-9

    # Setting the same start point for both datasets 
    start_plot_time = min(df_odom['time'].iloc[0], df_cmd['time'].iloc[0])

    df_odom['time'] = df_odom['time'] - start_plot_time
    df_cmd['time'] = df_cmd['time'] - start_plot_time

    print(df_odom['time'].iloc[0])
    print(df_odom['time'][0])
    

    print(df_cmd['time'].iloc[0])
    print(df_cmd['time'][0])


    # Create plots
    fig, axes = plt.subplots(2, 2, figsize=(15, 8))
    fig.suptitle('Velocidades Comandadas vs Reales', fontsize=16)
    
    # Plot 1: Linear velocity comparison
    axes[0, 0].plot(df_cmd['time'], df_cmd['linear_vel_x'], 'r--', 
                 label='Comando de Velocidad Lineal X', linewidth=2)
    axes[0, 0].plot(df_odom['time'], df_odom['linear_vel_x'], 'b-', 
                 label='Velocidad Lineal X Real', linewidth=1, alpha=0.7)
    axes[0, 0].set_xlabel('Tiempo (s)')
    axes[0, 0].set_ylabel('Velocidad Lineal (m/s)')
    axes[0, 0].set_title('Velocidad Lineal: Comandada vs Real')
    axes[0, 0].grid(True)
    axes[0, 0].legend()
    
    # Plot 2: Angular velocity comparison
    axes[1, 0].plot(df_cmd['time'], df_cmd['angular_vel_z'], 'r--', 
                 label='Comando de Velocidad Angular Z', linewidth=2)
    axes[1, 0].plot(df_odom['time'], df_odom['angular_vel_z'], 'b-', 
                 label='Velocidad Angular Z Real', linewidth=1, alpha=0.7)
    axes[1, 0].set_xlabel('Tiempo (s)')
    axes[1, 0].set_ylabel('Velocidad Angular (rad/s)')
    axes[1, 0].set_title('Velocidad Angular: Comandada vs Real')
    axes[1, 0].grid(True)
    axes[1, 0].legend()
    
    plt.tight_layout()
    output_path = os.path.join(output_dir, 'velocity_comparison.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Saved comparison plots to: {output_path}")
    plt.show()


def main():
    """Main function."""
    args = parse_args()
    
    # Determine file paths
    if args.log_dir and args.session:
        log_dir = os.path.expanduser(args.log_dir)
        odom_file = os.path.join(log_dir, f'odom_{args.session}.csv')
        cmd_vel_file = os.path.join(log_dir, f'cmd_vel_{args.session}.csv')
    else:
        odom_file = args.odom
        cmd_vel_file = args.cmd_vel
    
    # Create output directory
    output_dir = os.path.expanduser(args.output)
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    # Read data files
    df_odom = None
    df_cmd = None
    
    if odom_file and os.path.exists(os.path.expanduser(odom_file)):
        odom_file = os.path.expanduser(odom_file)
        print(f"Reading odometry data from: {odom_file}")
        df_odom = pd.read_csv(odom_file)
        print(f"Loaded {len(df_odom)} odometry records")
    else:
        print(f"Odometry file not found: {odom_file}")
    
    if cmd_vel_file and os.path.exists(os.path.expanduser(cmd_vel_file)):
        cmd_vel_file = os.path.expanduser(cmd_vel_file)
        print(f"Reading cmd_vel data from: {cmd_vel_file}")
        df_cmd = pd.read_csv(cmd_vel_file)
        print(f"Loaded {len(df_cmd)} cmd_vel records")
    else:
        print(f"Cmd_vel file not found: {cmd_vel_file}")
    
    # Generate plots
    if df_odom is not None:
        plot_odometry(df_odom, output_dir)
    
    # if df_cmd is not None:
    #     plot_cmd_vel(df_cmd, output_dir)
    
    if df_odom is not None and df_cmd is not None:
        plot_comparison(df_odom, df_cmd, output_dir)
    
    print("\nPlotting complete!")


if __name__ == '__main__':
    main()
